# Generated by Django 5.2.6 on 2025-10-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shiping_address',
            new_name='shipping_address',
        ),
    ]
