# Generated by Django 5.2.6 on 2025-09-29 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_full_name', models.CharField(max_length=250)),
                ('shipping_email', models.EmailField(max_length=250)),
                ('shipping_phone', models.CharField(blank=True, max_length=25)),
                ('shipping_address1', models.CharField(blank=True, max_length=250)),
                ('shipping_address2', models.CharField(blank=True, max_length=250, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=25)),
                ('shipping_state', models.CharField(blank=True, max_length=25)),
                ('shipping_zipcode', models.CharField(blank=True, max_length=25)),
                ('shipping_country', models.CharField(default='iran', max_length=25)),
                ('shipping_old_cart', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'shiping address',
            },
        ),
        migrations.DeleteModel(
            name='ShipingAddress',
        ),
    ]
