# Generated by Django 5.2.6 on 2025-10-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'در انتظار پرداخت '), ('Processing', 'در حال پردازش  '), ('shipped', 'ارسال شده ب پست  '), ('Delivered', 'تحویل داده شده  ')], default='pending', max_length=50),
        ),
    ]
