# Generated by Django 5.2.6 on 2025-10-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_shiping_address_order_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
