# Generated by Django 5.2.6 on 2025-10-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'در انتظار پرداخت '), ('Processing', 'در حال پردازش  '), ('shipped', 'ارسال شده ب پست  '), ('Delivered', 'تحویل داده شده  ')], default='Pending', max_length=50),
        ),
    ]
