# Generated by Django 5.2.6 on 2025-09-17 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customers_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(blank=True, upload_to='upload/product/'),
        ),
    ]
