# Generated by Django 5.2.6 on 2025-09-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_products_category_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address2',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
